### ISSUE TITLE
Getting 'No module named MySQLdb' while using sqlite3

### ISSUE THREAD

**Issue by nesanton** [sii/siptrackd#9]
Hi,
It seems that both storage engines are imported unconditionally here. Should they be?
https://github.com/sii/siptrackd/blob/4dc71d18eb617e8d0f3b2a07fd230e0cfb10b955/siptrackdlib/storage/__init__.py#L2

I'm using sqlite only
Commenting out stmysql import made it work

**Comment by stemid** [comment]
I assume you're getting import errors when you run siptrackd?

Yes they're both imported but that shouldn't be an issue unless you're missing the mysql client library in your install. 

It's really just a matter of installing the "mariadb-devel mariadb" packages for your distro, and complementing with the MySQL-python package which is already in requirements.txt for siptrackd. 

So it should be enough to follow the [install instructions](https://github.com/sii/siptrackweb/wiki/Installing-siptrackweb-in-virtualenv). 

But yeah they're imported unconditionally and that might not be optimal but it's very low priority to change so unless you submit a PR it probably won't get changed until after all the other enhancements.

**Comment by nesanton** [comment]
Yes, indeed while running siptrackd.

surely requirements.txt always worked and it's good enough. It's just this one system with compiled python. Still no problem, just extra steps

Thanks!
closing
